const quiz_science = [
    ["science", "la science"],
    ["exact sciences", "les sciences exactes"],
    ["social sciences", "les sciences sociales"],
    ["hard sciences", "les sciences dures"],
    ["soft sciences", "les sciences molles"],
    ["scientific progress", "les progrès scientifiques"],
    ["medical advances", "les progrès médicaux"],
    ["technological advances", "les progrès technologiques"],
    ["a scientist", "un scientifique"],
    ["the scientific community", "la communauté scientifique"],
    ["to be scientifically trained", "avoir une formation scientifique"],
    ["scientism", "le scientisme"],
    ["scientifically proven", "prouvé scientifiquement"],
    ["physics", "la physique"],
    ["a physicist", "un physicien"],
    ["chemistry", "la chimie"],
    ["a chemist", "un chimiste"],
    ["an astronomer", "un astronaute"],
    ["computer science", "l'informatique"],
    ["a computer scientist", "un informaticien"],
    ["knowledge", "la connaissance"],
    ["a theory", "une théorie"],
    ["theoretical", "théorique"],
    ["a hypothesis", "une hypothèse"],
    ["data", "des données"],
    ["evidence", "des preuves"],
    ["to have proof of something", "avoir la preuve de quelque chose"],
    ["to test a theory", "mettre une théorie à l'épreuve"],
    ["to call a belief into question", "remettre en cause une croyance"],
    ["to challenge an idea", "contester une idée"],
    ["disputable", "contestable"],
    ["indisputable", "incontestable"],
    ["research", "la recherche"],
    ["to do research", "faire de la recherche"],
    ["to carry out research into a subject", "faire des recherches sur un sujet"],
    ["cutting-edge research", "la recherche de pointe"],
    ["groundbreaking research", "des recherches révolutionnaires"],
    ["a research laboratory", "un laboratoire de recherches"],
    ["a research worker", "un chercheur"],
    ["a research fellow", "un chercheur attaché à une université"],
    ["a research student", "un doctorant"],
    ["fundamental research", "la recherche fondamentale"],
    ["applied research", "la recherche appliquée"],
    ["findings", "des résultats"],
    ["a discovery", "une découverte"],
    ["a breakthrough", "une percée"],
    ["a study", "une étude"],
    ["to conduct a study", "mener une étude"],
    ["a paper", "un article"],
    ["a journal", "une revue scientifique"],
    ["a scholar", "un érudit"],
    ["an academic", "un universitaire"],
    ["an experiment", "une expérience"],
    ["a phenomenon", "un phénomène"],
    ["to carry out an experiment", "faire une expérience"],
    ["to experiment on mice", "faire des expériences sur des souris"],
    ["to experiment with a new vaccine", "expérimenter un nouveau vaccin"],
    ["a laboratory", "un laboratoire"],
    ["a guinea pig", "un cobaye"],
    ["research and development", "recherche et développement"],
    ["to develop", "mettre au point"],
    ["to try out a technique", "essayer une technique"],
    ["to devise", "concevoir"],
    ["a device", "un appareil"],
    ["to design", "élaborer"],
    ["a prototype", "un prototype"],
    ["a model", "un modèle"],
    ["a blueprint", "un plan"],
    ["technology", "technologie"],
    ["technical", "technique"],
    ["a technician", "un technicien"],
    ["a technicality", "un détail technique"],
    ["a science park", "une technopole"],
    ["the technorati", "les gens qui ont une compétence technique"],
    ["a technophobe", "un technophobe"],
    ["technophobic", "technophobe"],
    ["technofear", "la technophobie"],
    ["technocracy", "la technocratie"],
    ["to improve", "améliorer"],
    ["to upgrade", "mettre à jour"],
    ["to revolutionize", "révolutionner"],
    ["a revolutionary technique", "une technique révolutionnaire"],
    ["a patent", "un brevet"],
    ["to innovate", "innover"],
    ["an innovation", "une innovation"],
    ["an inventor", "un inventeur"],
    ["inventive", "inventif"],
    ["creative", "créatif"],
    ["inventiveness", "inventivité"],
    ["creativity", "créativité"],
    ["a pioneer", "un pionnier"],
    ["to act as a pioneer", "faire oeuvre de pionnier"],
    ["pioneer work", "un travail novateur"],
    ["to pioneer the study of something", "être l'un des premiers à étudier quelque chose"],
    ["an engine", "un moteur"],
    ["an engineer", "un ingénieur"],
    ["engineering", "l'ingéniérie"],
    ["civil engineering", "le génie civil"],
    ["robotics", "la robotique"],
    ["electronics", "l'électronique"],
    ["mechanics", "la mécanique"],
    ["a mechanism", "un mécanisme"],
    ["machinery", "la machinerie"],
    ["to operate a system", "faire fonctionner un système"],
    ["equipment", "le matériel"],
    ["a gadget", "un gadget"],
    ["a gizmo", "un machin"],
    ["state-of-the-art", "dernier cri"],
    ["to be tech-savvy", "être calé en matière de technologies"],
    ["a mobile phone", "un téléphone portable"],
    ["a wireless device", "un appareil sans fil"],
    ["a smartphone", "un téléphone intelligent"],
    ["a touch-screen", "un écran tactile"],
    ["a sensor", "un capteur"]
];

// TOUS LES QUIZS SONT DANS LA VARIABLE QUIZS

const Quizs = {
    "science": quiz_science,
};