const quiz_science = [
    ["science", "la science"],
    ["exact sciences", "les sciences exactes"],
    ["social sciences", "les sciences sociales"],
    ["hard sciences", "les sciences dures"],
    ["soft sciences", "les sciences molles"],
    ["scientific progress", "les progrès scientifiques"],
    ["medical advances", "les progrès médicaux"],
    ["technological advances", "les progrès technologiques"],
    ["a scientist", "un scientifique"],
    ["the scientific community", "la communauté scientifique"],
    ["to be scientifically trained", "avoir une formation scientifique"],
    ["scientism", "le scientisme"],
    ["scientifically proven", "prouvé scientifiquement"],
    ["physics", "la physique"],
    ["a physicist", "un physicien"],
    ["chemistry", "la chimie"],
    ["a chemist", "un chimiste"],
    ["an astronomer", "un astronaute"],
    ["computer science", "l'informatique"],
    ["a computer scientist", "un informaticien"],
    ["knowledge", "la connaissance"],
    ["a theory", "une théorie"],
    ["theoretical", "théorique"],
    ["a hypothesis", "une hypothèse"],
    ["data", "des données"],
    ["evidence", "des preuves"],
    ["to have proof of something", "avoir la preuve de quelque chose"],
    ["to test a theory", "mettre une théorie à l'épreuve"],
    ["to call a belief into question", "remettre en cause une croyance"],
    ["to challenge an idea", "contester une idée"],
    ["disputable", "contestable"],
    ["indisputable", "incontestable"],
    ["research", "la recherche"],
    ["to do research", "faire de la recherche"],
    ["to carry out research into a subject", "faire des recherches sur un sujet"],
    ["cutting-edge research", "la recherche de pointe"],
    ["groundbreaking research", "des recherches révolutionnaires"],
    ["a research laboratory", "un laboratoire de recherches"],
    ["a research worker", "un chercheur"],
    ["a research fellow", "un chercheur attaché à une université"],
    ["a research student", "un doctorant"],
    ["fundamental research", "la recherche fondamentale"],
    ["applied research", "la recherche appliquée"],
    ["findings", "des résultats"],
    ["a discovery", "une découverte"],
    ["a breakthrough", "une percée"],
    ["a study", "une étude"],
    ["to conduct a study", "mener une étude"],
    ["a paper", "un article"],
    ["a journal", "une revue scientifique"],
    ["a scholar", "un érudit"],
    ["an academic", "un universitaire"],
    ["an experiment", "une expérience"],
    ["a phenomenon", "un phénomène"],
    ["to carry out an experiment", "faire une expérience"],
    ["to experiment on mice", "faire des expériences sur des souris"],
    ["to experiment with a new vaccine", "expérimenter un nouveau vaccin"],
    ["a laboratory", "un laboratoire"],
    ["a guinea pig", "un cobaye"],
    ["research and development", "recherche et développement"],
    ["to develop", "mettre au point"],
    ["to try out a technique", "essayer une technique"],
    ["to devise", "concevoir"],
    ["a device", "un appareil"],
    ["to design", "élaborer"],
    ["a prototype", "un prototype"],
    ["a model", "un modèle"],
    ["a blueprint", "un plan"],
    ["technology", "technologie"],
    ["technical", "technique"],
    ["a technician", "un technicien"],
    ["a technicality", "un détail technique"],
    ["a science park", "une technopole"],
    ["the technorati", "les gens qui ont une compétence technique"],
    ["a technophobe", "un technophobe"],
    ["technophobic", "technophobe"],
    ["technofear", "la technophobie"],
    ["technocracy", "la technocratie"],
    ["to improve", "améliorer"],
    ["to upgrade", "mettre à jour"],
    ["to revolutionize", "révolutionner"],
    ["a revolutionary technique", "une technique révolutionnaire"],
    ["a patent", "un brevet"],
    ["to innovate", "innover"],
    ["an innovation", "une innovation"],
    ["an inventor", "un inventeur"],
    ["inventive", "inventif"],
    ["creative", "créatif"],
    ["inventiveness", "inventivité"],
    ["creativity", "créativité"],
    ["a pioneer", "un pionnier"],
    ["to act as a pioneer", "faire oeuvre de pionnier"],
    ["pioneer work", "un travail novateur"],
    ["to pioneer the study of something", "être l'un des premiers à étudier quelque chose"],
    ["an engine", "un moteur"],
    ["an engineer", "un ingénieur"],
    ["engineering", "l'ingéniérie"],
    ["civil engineering", "le génie civil"],
    ["robotics", "la robotique"],
    ["electronics", "l'électronique"],
    ["mechanics", "la mécanique"],
    ["a mechanism", "un mécanisme"],
    ["machinery", "la machinerie"],
    ["to operate a system", "faire fonctionner un système"],
    ["equipment", "le matériel"],
    ["a gadget", "un gadget"],
    ["a gizmo", "un machin"],
    ["state-of-the-art", "dernier cri"],
    ["to be tech-savvy", "être calé en matière de technologies"],
    ["a mobile phone", "un téléphone portable"],
    ["a wireless device", "un appareil sans fil"],
    ["a smartphone", "un téléphone intelligent"],
    ["a touch-screen", "un écran tactile"],
    ["a sensor", "un capteur"]
];

const quiz_women = [
    ["female", "du sece féminin"],
    ["women's status in society", "la place des femmes dans la société"],
    ["gender imbalance", "le déséquilibre entre les sexes"],
    ["gender inequalities", "les inégalités entre les hommes et les femmes"],
    ["gender war", "la guerre entre les sexes"],
    ["a chauviniste", "un phallocrate"],
    ["machismo", "le machisme"],
    ["misoginy", "la misogynie"],
    ["a misoginist", "un misogyne"],
    ["sexism", "le sexisme"],
    ["sexist prejudice", "des préjugés sexistes"],
    ["fenimism", "le féminisme"],
    ["the Women's Movement", "le mouvement des femmes"],
    ["the women's rights movement", "le mouvement pour les droits de la femme"],
    ["to become emancipated", "s'émanciper"],
    ["to empower women", "rendre les femmes autonomes"],
    ["a forced marriage", "un mariage forcé"],
    ["an arranged marriage", "un mariage arangé"],
    ["a sham marriage", "un mariage blanc"], // rajouter a marriage a convenience
    ["a dowry", "un dot"],
    ["polygamy", "la polygamie"],
    ["polygamous", "polygame"],
    ["female genital mutilation", "l'excision"],
    ["a battered wife", "une femme battue"],
    ["domestic violence", "violence conjugale"],
    ["the right to vote", "le droit de vote"],
    ["to become pregnant", "tomber enceinte"],
    ["women of childbearing age", "les femmes en âge d'avoir des enfants"],
    ["the pill", "la pilule"],
    ["the contraceptive pill", "la pilule contraceptive"],
    ["to be on the pull", "prendre la pilule"],
    ["to go on maternity leave", "prendre congé maternité"],
    ["parental leave", "congé parental"],
    ["to look after one's children", "s'occuper de ses enfants"],
    ["to bring up a child", "élever un enfant"],
    ["child rearing", "l'éducation des enfants"],
    ["a housewife", "une femme au foyer"],
    ["to do the housework", "faire le ménage"],
    ["to do the cooking", "faire la cuisine"],
    ["to do the washing", "faire la lessive"],
    ["to do the washing-up", "faire la vaisselle"],
    ["to do the shopping", "faire les courses"],
    ["to vacuum", "passer l'aspirateur"],
    ["domestic appliances", "les appareils ménagers"],
    ["household chores", "les tâches ménagères"],
    ["to be faced with a dilemma", "être confronté à un dilemme"],
    ["a nursery", "une crèche"],
    ["a day-care centre", "une garderie"],
    ["a nanny", "une nounou"],
    ["a childminder", "une nourrice"],
    ["to balance work and family", "trouver un équilibre entre travail et famille"],
    ["to juggle a career and a family", "jongler pour concilier carrière et famille"],
    ["to reconcile", "concilier"],
    ["family responsibilities", "les responsabilités familiales"],
    ["to be financially dependant on somebody", "être dépendant financièrement de quelqu'un"],
    ["to earn a living", "gagner sa vie"],
    ["to support one's family", "subvenir aux besoins de sa famille"],
    ["to feed one's children", "nourrir ses enfants"],
    ["to be the breadwinner", "être celui qui fait vivre sa famille"],
    ["she is the family wage earner", "c'est elle qui fait vivre sa famille"],
    ["to bring home the bacon", "faire bouillir la marmite"],
    ["female labour", "la main d'oeuvre féminine"],
    ["female employment", "l'emploi des femmes"],
    ["women make up x% of the workforce", "les femmes représentent x% de la main d'oeuvre"],
    ["to have a career", "faire carrière"],
    ["to be a working woman", "être une femme qui travaille"],
    ["a career woman", "une femme qui fait carrière"],
    ["to work part time", "travailler à temps partiel"],
    ["to work full time", "travailler à plein temps"],
    ["equal pay", "l'égalité des salaires"],
    ["the gender pay gap", "le différenciel de salaire entre les sexes"],
    ["to appoint somebody to a post", "nommer quelqu'un à un poste"],
    ["to compete with men", "être en concurrence avec les hommes"],
    ["a responsible job", "un poste à responsabilités"],
    ["a top job", "un poste à haut niveau"],
    ["a menial job", "un emploi subalterne"],
    ["to have a successful career", "réussir sa carrière"],
    ["barriers to female advancement", "les obstacles à la promotion des femmes"],
    ["a male preserve", "une chasse gardée pour les hommes"],
    ["to discriminate against somebody", "introduire une discrimination contre quelqu'un"],
    ["to be discriminated against", "être victime de discrimination"],
    ["harassment", "le harcèlement"],
    ["sexual harassment", "le harcèlement sexuel"],
    ["parity", "la parité"],
    ["under-represented", "sous-représenté"],
    ["to introduce quotas", "instaurer des quotas"],
    ["the introduction of quotas", "l'instauration de quotas"],
    ["affirmative action", "la discrimination positive"],
    ["equal opportunity", "l'égalité des chances"],
    ["egalitarian", "égalitaire"],
    ["egalitarianism", "l'égalitarisme"],
    ["to achieve equality with men", "atteindre l'égalité avec les hommes"]
];

// TOUS LES QUIZS SONT DANS LA VARIABLE QUIZS

const Quizs = {
    "science": quiz_science,
    "women": quiz_women
};